version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fswbarber
    ports:
      - "5432:5432"
    volumes:
      - polls_pg_data:/bitnami/postgresql
volumes:
  polls_pg_data:
