import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { Footer } from "./_components/footer"
import { Toaster } from "./_components/ui/sonner"
import { AuthProvider } from "./_providers/auth"
import "./globals.css"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})
  
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} antialiased`}
      >
        <AuthProvider>
          <div className="flex flex-col h-lvh">
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
